### ISSUE TITLE
PLACES

### ISSUE THREAD

**Issue by DominicSimpson** [fac26/CatsDogsOrMovies#29]
Hiya, there are a couple of issues with the places tab:
- Some CSS would be good on the eye, rather than none at all. 
- I'm not quite sure what the Unique button in the Enter a Unique Postcode does, as it seems to generate a unique postcode anyway. I tried entering in my own postcode, to see what would happen, and nothing did.

**Comment by d0g3bl2** [comment]
Thanks @DominicSimpson 

These issues have both been resolved 

Gal
