### ISSUE TITLE
Decide on which APIs we will use

### ISSUE THREAD

**Issue by Psydwinder** [fac26/CatsDogsOrMovies#4]
This issue has been raised to help document the teams decisions when it came to picking which public API to use.

**Comment by d0g3bl2** [comment]
# From Dogs to Postcodes 

Initially I was going to use the Dog API https://dog.ceo/dog-api but after looking at the documentation I decided that the ways I could use the data would be to limited. Although Dog API provides many different endpoints I felt limited by arrays of dog breeds or images of breeds. 

I decided to use the Postcode & Geo-location API for the UK https://postcodes.io/ as they offer many endpoints and the data is more complex, enabling me to create a user experience that is hopefully engaging, humorous and interesting.  

Gal

**Comment by d0g3bl2** [comment]
I have used the Postcode & Geo-location API for the UK https://postcodes.io/ and now I am going to use the https://data.police.uk/docs/method/neighbourhood-locate/ API to return information about the local police force of the area the user is searching.

This will provide the user with more in depth information about their chosen destination. 

Gal
